version: "2.2"

services:
  backend:
    image: tinkoff-edu-app:1.0.0
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      app:
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      MYSQL_URL: 'jdbc:mysql://db/petclinic'

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      app:
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_ROOT_PASSWORD:
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"

networks:
  app:
